name: Build Publish
on:
  push:
    branches:
      - main
    paths-ignore:
      - "package.json"
      - "CHANGELOG.md"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN_ACTION }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: inlustra/autodockerdash:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Bump version and push tag
        uses: TriPSs/conventional-changelog-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN_ACTION }}
          git-message: "chore(release): {version}"
          tag-prefix: ""
          output-file: "CHANGELOG.md"
