name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: 'Release GitHub, Docker'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Get version from package.json after release step
        id: extractver
        run: echo "::set-output name=version::$(yarn get-version --silent)"
      - name: Release to Docker
        if: steps.initversion.outputs.version != steps.extractver.outputs.version
        run: |
          echo ${{secrets.DOCKER_PASSWORD}} | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
          yarn docker:build
          docker tag inlustra/autodockerdash:latest inlustra/autodockerdash:${{ steps.extractver.outputs.version }}
          docker push inlustra/autodockerdash:${{ steps.extractver.outputs.version }}
          docker push inlustra/autodockerdash:latest
      - name: Create Pull Request with updated package files
        if: steps.initversion.outputs.version != steps.extractver.outputs.version
        uses: peter-evans/create-pull-request@v2.4.4
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: 'chore(release): ${{ steps.extractver.outputs.version }}'
          committer: add-bot <thomas@thenairn.com>
          author: add-bot <thomas@thenairn.com>
          title: 'chore(release): ${{ steps.extractver.outputs.version }}'
          body: 'Version bump in package.json and package-lock.json for release [${{ steps.extractver.outputs.version }}](https://github.com/${{github.repository}}/releases/tag/v${{ steps.extractver.outputs.version }})'
          branch: version-bump/${{ steps.extractver.outputs.version }}